// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('GoogleSearch', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('GoogleSearch', async function() {
    await driver.get("https://www.google.com.mx/")
    await driver.setRect(1764, 1017)
    await driver.findElement(By.name("q")).sendKeys("Selenium")
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".bkWMgd > .g > div > .rc .ellip")).click()
    vars["win5942"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win5942"])
    await driver.findElement(By.linkText("Documentation")).click()
    await driver.findElement(By.linkText("Selenium IDE")).click()
    await driver.findElement(By.css(".related:nth-child(3) .right:nth-child(2) > a")).click()
    await driver.findElement(By.linkText("Download")).click()
    await driver.findElement(By.linkText("edit this page")).click()
    await driver.switchTo().window(vars["root"])
    {
      const element = await driver.findElement(By.id("_RcWOXeCVJoPIsQWjlKuYCg65"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,291)")
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".bkWMgd:nth-child(3) .g:nth-child(1) .ellip")).click()
    vars["win660"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win660"])
    await driver.findElement(By.css("p:nth-child(2) > a:nth-child(5)")).click()
  })
})
