// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('FieldsTestCase', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('FieldsTestCase', async function() {
    await driver.get("http://localhost:8080/SeleniumWebServerTest/")
    await driver.setRect(1085, 968)
    await driver.findElement(By.name("nombre")).click()
    await driver.findElement(By.name("nombre")).sendKeys("Jezreel arturo")
    await driver.findElement(By.name("apellido")).click()
    await driver.findElement(By.name("apellido")).sendKeys("Avila")
    await driver.findElement(By.css("input:nth-child(7)")).click()
    await driver.findElement(By.name("apellido")).click()
  })
})
