// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('LocalMultiplesVentanas', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    // await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('LocalMultiplesVentanas', async function() {
    await driver.get("http://localhost:8080/SeleniumWebServerTest/")
    // await driver.setRect(1764, 1017)
    await driver.findElement(By.linkText("Second page")).click()
    await driver.findElement(By.linkText("First page")).click()
    await driver.findElement(By.name('nombre')).sendKeys('Jezreel')
    vars["windowHandles"] = await driver.getAllWindowHandles()
    console.log('windowHandles='+vars["windowHandles"])
    await driver.findElement(By.linkText("Third page")).click()
    vars["win8657"] = await waitForWindow(2000)
    console.log('win8657='+vars["win8657"])
    vars["root"] = await driver.getWindowHandle()
    console.log('root='+vars["root"])
    await driver.switchTo().window(vars["win8657"])
    await driver.findElement(By.linkText("Fourth page")).click()
    await driver.findElement(By.linkText("third page")).click()
    await driver.findElement(By.linkText("First page")).click()
    await driver.findElement(By.linkText("Second page")).click()
    await driver.findElement(By.id('name')).sendKeys('Jez Jon Jonz')
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.linkText("Third page")).click()
    vars["win6533"] = await waitForWindow(2000)
    console.log('win6533='+vars["win6533"])
    await driver.switchTo().window(vars["win6533"])
    await waitForWindow(2000)
    await driver.switchTo().window(vars["win8657"])
    await waitForWindow(2000)
    await driver.switchTo().window(vars["win6533"])
    await waitForWindow(2000)
    await driver.switchTo().window(vars["win8657"])
    await waitForWindow(2000)
    await driver.switchTo().window(vars["root"])
    await waitForWindow(2000)
    await driver.switchTo().window(vars["win6533"])
    await waitForWindow(4000)
  })
})
