// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('LocalTestCase', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('LocalTestCase', async function() {
    await driver.get("http://localhost:8080/SeleniumWebServerTest/")
    // await driver.setRect(1764, 1017)
    vars["indexHandles"] = await driver.getAllWindowHandles()
    await console.log('indexHandles: ' + vars["indexHandles"])
    await driver.sleep(2500)
    await driver.findElement(By.linkText("Second page")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await console.log('windowHandles: ' + vars["windowHandles"])
    await driver.sleep(1500)

    // Open second tab and focus it
    await driver.findElement(By.linkText("Third page")).click()
    vars["win9271"] = await waitForWindow(3000)
    await console.log('win9271: ' + vars["win9271"])
    await driver.sleep(1500)
    await driver.switchTo().window(vars["win9271"])
    await driver.sleep(1500)
    // await driver.findElement(By.linkText("First page")).click()
    await console.log('indexHandles: linea[44]' + vars["indexHandles"])
    await driver.switchTo().window(vars["indexHandles"])
  })
})
